# Default config for ZavMessage.
# Make sure all your messages are inside of single quotes. (This makes sure that color and special characters work properly)
# If you want to make your own line breaks MAKE SURE WORDWRAP IS FALSE!!! Custom line breaks are only supported when wordwrap is off.

enabled: true

wordwrap: true

delay: 60 # In Seconds

permissionsenabled: false # If true, only people with permission can view the message.

chatformat: '[&6ZavMessage&f]: %msg'

messageinrandomorder: false # Should the messages be displayed in a random order

messagesinconsole: true

requireplayersonline: true

dontrepeatrandommessages: true

messages:
    default:
    - '&6Example Message'
    - 'Thanks for choosing this plugin :D!'
    - 'Test Message'
    - '&4Made by zachooo and javoris767!'