name: ZavMessage

version: ${project.version}

description: Automatically send predefined messages to the server.

author: zachoooo

main: io.github.zachoooo.ZavMessage

commands:
    automessager:
        description: Commands for this plugin
        aliases: am